# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --dev
    - uv run python -m sphinx docs $READTHEDOCS_OUTPUT/html -b html
