name: mapmaker
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-env:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install dependencies
        run: uv sync

      - name: Run mapmaker
        run: |
          python runmaker.py \
            --output ./flatmaps \
            --source https://github.com/AnatomicMaps/rat-flatmap.git \
            --commit curation \
            --manifest manifest.json \
            --force \
            --no-path-layout \
            --background-tiles
