name: mapmaker
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-env:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Set Poetry environment
        run: |
          poetry env use 3.10

      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install --no-root

      - name: Run mapmaker
        run: |
          poetry run python runmaker.py \
            --output ./flatmaps \
            --source https://github.com/AnatomicMaps/rat-flatmap.git \
            --manifest manifest.json \
            --background-tiles
