name: mapmaker
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  create-env:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          auto-activate-base: false
          activate-environment: mapmaker
          environment-file: envs/mapmaker.yaml

      - name: Run mapmaker
        run: |
          python runmaker.py \
            --output ./flatmaps \
            --source https://github.com/AnatomicMaps/rat-flatmap.git \
            --commit curation \
            --manifest manifest.json \
            --force \
            --background-tiles
